name: Build Docker Image on PR

on:
  pull_request:
    branches: [main]
  workflow_dispatch:  # <-- this allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract tag from PR title
      id: extract_tag
      run: |
        TAG=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[0-9]+\.[0-9]+')
        if [[ -z "$TAG" ]]; then
          echo "❌ Tag not found in PR title. Use format like 'Release 1.1'"
          exit 1
        fi
        echo "✅ Tag extracted: $TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build image (no push)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: guilhermelinsc/rstudio-ms:${{ steps.extract_tag.outputs.tag }}

