name: Push Docker Image on Merge

on:
  push:
    branches: [main]
  workflow_dispatch:  # <-- this allows manual runs


jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract tag from commit message
      id: extract_tag
      run: |
        TAG=$(git log -1 --pretty=%B | grep -oE '[0-9]+\.[0-9]+')
        if [[ -z "$TAG" ]]; then
          echo "❌ Tag not found in commit message. Use format like 'Release 1.1'"
          exit 1
        fi
        echo "✅ Tag extracted: $TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: guilhermelinsc/rstudio-ms:${{ steps.extract_tag.outputs.tag }}

